### PR TITLE
RHSSO-1950 OCP templates point to the wrong repository in their descr…

### PR DESCRIPTION
**Pull request by Pepo48**
…iptions

* updated the templates' descriptions

Signed-off-by: Peter Zaoral <pzaoral@redhat.com>

### CODE REVIEW

**Comment by iankko** [comment]
@Pepo48 Thx for the fix, Peter! But (while at this) could you possible update the branch name in the `docs` entries, too? (see below):

```
$ git status
On branch sso75-dev
Your branch is up to date with 'origin/sso75-dev'.

nothing to commit, working tree clean

```

```
$ grep -rHn 'sso75-cpaas-dev' *
docs/templates/sso75-x509-postgresql-persistent.adoc:12:An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.
docs/templates/sso75-x509-https.adoc:12:An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.
docs/templates/sso75-postgresql.adoc:12:An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.
docs/templates/sso75-postgresql-persistent.adoc:12:An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.
docs/templates/sso75-ocp4-x509-postgresql-persistent.adoc:12:An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.
docs/templates/sso75-ocp4-x509-https.adoc:12:An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.
docs/templates/sso75-https.adoc:12:An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.
docs/README.adoc:10:Source can be found https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev[here].
README.adoc.in:4:Source can be found https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev[here].
templates/sso75-x509-postgresql-persistent.json:11:            "description": "An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.",
templates/sso75-x509-https.json:11:            "description": "An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.",
templates/sso75-postgresql.json:11:            "description": "An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.",
templates/sso75-postgresql-persistent.json:11:            "description": "An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.",
templates/sso75-ocp4-x509-postgresql-persistent.json:11:            "description": "An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.",
templates/sso75-ocp4-x509-https.json:11:            "description": "An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.",
templates/sso75-https.json:11:            "description": "An example application based on RH-SSO 7.5 on OpenJDK image. For more information about using this template, see https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev/docs.",
```

**Review by iankko — CHANGES_REQUESTED** [review]
See previous comment

**Comment by Pepo48** [comment]
@iankko thanks for the review. I updated even the doc files as you requested.

**Comment by iankko** [comment]
> @iankko thanks for the review. I updated even the doc files as you requested.

@Pepo48 Thx! The latest version LGTM.

**Review by iankko — APPROVED** [review]
LGTM

**Pull request merged**
