### PR TITLE
[KEYCLOAK-18763] 7.4.9 Rebase RH-SSO z-stream image stream on top of …

### PR DESCRIPTION
**Pull request by sguilhen**
…EAP z-stream image

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by drichtarik — CHANGES_REQUESTED** [review]
in image.yaml on lines 137 - 140 you need to update the eap patch artifact according to the EAP artifact

**Comment by sguilhen** [comment]
@drichtarik Fixed

**Comment by drichtarik** [comment]
LGTM

**Review by iankko — APPROVED** [review]
LGTM AFAICT @sguilhen Thanks for your change! (see below for more verbose check)

```
(First in my local copy of the sso74-dev branch)
1. $ grep -rHn '7\.4\.8' * | cut -d ':' -f1 > /tmp/files
2. $ for file in $(cat /tmp/files); do sed -i 's/7.4.8.GA/7.4.9.GA/g' $file; done
3. Then update "jboss-eap-modules.git", "jboss-eap-7-image.git" & "cct_module.git" to latest available tags in the image.yaml,
4. Update JBoss EAP patch location & md5sum in the image.yaml
5. git diff > /tmp/expected_change
6.  $ curl -so /tmp/stefans_change.diff https://github.com/sguilhen/redhat-sso-7-openshift-image/commit/a5c1bbab91e15c40e270813a6e18906dcf354a1a.diff
7. $ diff -s /tmp/expected_change /tmp/stefans_change.diff 
Files /tmp/expected_change and /tmp/stefans_change.diff are identical
```

**Pull request merged**
