### PR TITLE
[RHSSO-1937] ensure expiry works in Infinispan

### PR DESCRIPTION
**Pull request by ahus1**
Setting any lifespan will enable the Infinispan reaper process to remove expired entries.

https://issues.redhat.com/browse/RHSSO-1937

---

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [x] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted
- [x] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by ahus1** [comment]
Hi @iankko - I'd be happy if you could perform a review of this PR. I made the changes to my best knowledge I gathered in the upstream project, still I don't know how to build/test this. I'd be happy if you could fill that gap by either building/testing it, or showing me how to do this.

**Comment by iankko** [comment]
Testing RH-SSO container image build (use the actual Jenkins server domain name to access it):
* https://keycloak.jenkins.server.com/view/RH-SSO/job/rh-sso-pipeline-continuous_container/527/

**Comment by iankko** [comment]
> Hi @iankko - I'd be happy if you could perform a review of this PR. I made the changes to my best knowledge I gathered in the upstream project, still I don't know how to build/test this. I'd be happy if you could fill that gap by either building/testing it, or showing me how to do this.

Hey @ahus1 , thx for your change! FWIW regarding testing, we don't build RH-SSO container images manually anymore to test some PR (while it's still technically feasible, not too much straightforward due to the amount of dependencies / artifacts, that need to be pre-downloaded / present in CEKit cache prior to launching of the build). Instead of that, it's enough to modify couple of parameters on corresponding Jenkins pipeline build. Namely:
* Switch the `RELEASE` parameter to `false` (since it's just testing build),
* Add the new `IMAGE_OPENSHIFT_REPO` param pointing to your GitHub's fork,
* Add the new `IMAGE_OPENSHIFT_BRANCH` param pointing to the GitHub branch within the fork, containing the change.

Then reschedule / rebuild / rerun some previous release build with these paramaters, and a new (scratch / testing) RH-SSO container image will be built for you.

For now, I have scheduled one for you (see previous comment). Will get to the PR review, once the image is built & I have had chance to play a bit with it.

Thx!
Jan

**Comment by andreaTP** [comment]
@ahus1 do you think this is something we should set in the Quarkus distribution as well?
https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/resources/cache-ispn.xml

cc. @pedroigor

**Comment by pedroigor** [comment]
@andreaTP AFAIK, this is only needed in Wildfly due to how the ISPN subsystem is implemented so you need to set a value in order to start the reaper threads. 

In the Quarkus dist we are using ISPN directly and the thread should be enabled.

**Comment by ahus1** [comment]
@andreaTP - the problem was that in Wildfly disabled the reaper thread explicitly upon settings on the other attributes. See #10461 for the parent issue. 

By default, the reaper is always enabled for Infinispan and it will run ever 60 seconds. I just downloaded the Quarkus nightly distribution, started it in dev mode, enabled the Infinispan cache and put a breakpoint in ExpirationManagerImpl.start() and ExpirationManagerImpl.processExpiration(). The code is called and executed, thereby it is safe to assume that this works as expected.

**Comment by andreaTP** [comment]
@pedroigor and @ahus1 thanks a lot for double checking!

**Review by iankko — CHANGES_REQUESTED** [review]
@ahus1 Thanks for the PR, Alexander! Sorry to bother, but could you possibly redo it
against a `sso75-dev` branch, rather than `sso75-cpaas-dev` branch?

The change LGTM from the technical PoV, but need to test with for a bit with the candidate
container image. Tried to switch the branches for you (base it on top of the `sso75-dev` one,
we use for building, rather than the original `sso75-cpaas-dev` one, but it resulted in a huge
pile of changed files to be included).

If it's not convenient to redo the PR, I can just `git format-patch` from your branch with
your latest change, and `git am` it back on top of `sso75-dev` branch.

Whatever version of how to get this included works for me. Just choose the one,
which works for you better.

Yet P.S.: Sorry for not looking into this sooner, but looks it has been quite some
time we have been building 7.5.X image last time.

**Comment by iankko** [comment]
Replaced by https://github.com/jboss-container-images/redhat-sso-7-openshift-image/pull/257 one, closing.

**Pull request closed without merging**
