### PR TITLE
Bacport and update 

### PR DESCRIPTION
**Pull request by drichtarik**

### CODE REVIEW

**Comment by drichtarik** [comment]
@iankko @pskopek @levivic

**Comment by levivic** [comment]
LGTM!

**Comment by iankko** [comment]
Since the commit shas are different, checking the particular commit changes as follows:

1) For `https://github.com/drichtarik/redhat-sso-7-openshift-image/tree/sso75-cpaas-dev` branch
```
 git clone -b sso75-cpaas-dev git@github.com:drichtarik/redhat-sso-7-openshift-image.git
```
Generate the diff (list of all changes) for last 9 commits:
```
$ git diff 4bf6d39d8085196b48203950f9f553f52b45cdfb ef58641f449e4886300247246c4f7bceacb464b7 > /tmp/denis.diff
```
2) Then for the `https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tree/sso75-dev` perform the same:
```
git clone -b sso75-dev git@github.com:jboss-container-images/redhat-sso-7-openshift-image.git
```
And generate the diff (list of all changes) for those commits present in `sso75-dev` branch, but not in `sso75-cpaas-dev` branch yet:
```
$ git diff 1a7c69834e78dc3e521cfa6c4ec0de94563ba829 760939b4904d3ed5f255a49b3a2f6222f4cb48e7 > /tmp/jboss_container_images.diff
```

Finally compare the two diffs to see if they are equal (contain same changes):
```
$ diff /tmp/denis.diff /tmp/jboss_container_images.diff 
1317a1318,1332
> diff --git a/modules/eap/setup/eap/modules/module.yaml b/modules/eap/setup/eap/modules/module.yaml
> index 1b068cd..e9a3ec6 100644
> --- a/modules/eap/setup/eap/modules/module.yaml
> +++ b/modules/eap/setup/eap/modules/module.yaml
> @@ -31,8 +31,8 @@ ports:
>  artifacts:
>  - name: eap-image-maven-repo
>    target: maven-repo.zip
> -  md5: 244700ed92787ad537e360069d9ca9b1
> -  url: http://$DOWNLOAD_SERVER/released/JBoss-middleware/eap7/7.4.0/jboss-eap-7.4.0-image-builder-maven-repository.zip
> +  md5: 115acd5c7fbcaea84f843c593e850515
> +  url: http://$DOWNLOAD_SERVER/devel/candidates/middleware/eap/JBEAP-7.4.2.GA-CR1/jboss-eap-7.4.2.GA-CR1-image-builder-maven-repository.zip
>  # CIAM-711: Update RH-SSO server overlay to 'RH-SSO 7.5.0.CR4' build
>  - name: keycloak-server-overlay.zip
>    md5: 4150d09f7bf5d524b4173f8850a06617
```

The only difference is, the jboss-container images diff contains also update of `boss-eap-7.4.0-image-builder-maven-repository.zip` to `jboss-eap-7.4.2.GA-CR1-image-builder-maven-repository.zip`, while the CPaaS version not.

But I think this is correct due the way CPaaS handles artifacts (IOW they are provided to CPaaS separately). @drichtarik is that correct? (IOW that image-biulder maven repo change doesn't need to be present in CPaaS, right?)

**Comment by drichtarik** [comment]
Yes I deliberately left out those commits. It's in the overrides

**Comment by iankko** [comment]
> Yes I deliberately left out those commits. It's in the overrides

Ok, thx for clarification (confirmed the md5sum in overrides matches), ACK for the change

**Review by iankko — APPROVED** [review]
LGTM, see previous comments for details

**Pull request merged**
