### PR TITLE
[RHSSO-2205] Organize the existing RH-SSO OpenShift templates more logically

### PR DESCRIPTION
**Pull request by iankko**
[RHSSO-2205] Organize the existing RH-SSO OpenShift templates more logically
    
    So for each of them it's clear:
    
    * What kind of TLS termination ('passthrough' vs 're-encrypt') the
      template is using,
    * What version of OpenShift (3.X vs 4.X) it's intended to be used for
    
    Also update the long description of the re-encrypt templates to describe
    the difference between the original service-serving CA bundle from
    '/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt' (3.X) and
    the new CA bundle that is automatically injected into any configMap annotated
    with 'service.beta.openshift.io/inject-cabundle=true' annotation
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
@andymunro PTAL too once got a chance

Thanks,
Jan

**Comment by iankko** [comment]
Comment about testing:
```
$ git clone -b RHSSO-2205 git@github.com:iankko/redhat-sso-7-openshift-image.git
```

```
$ cd redhat-sso-7-openshift-image/templates/
```

```
$ tree
.
├── passthrough
│   ├── sso76-https.json
│   ├── sso76-postgresql.json
│   └── sso76-postgresql-persistent.json
├── reencrypt
│   ├── ocp-3.x
│   │   ├── sso76-ocp3-x509-https.json
│   │   └── sso76-ocp3-x509-postgresql-persistent.json
│   └── ocp-4.x
│       ├── sso76-ocp4-x509-https.json
│       └── sso76-ocp4-x509-postgresql-persistent.json
├── scripts
│   └── gen_template_docs.py
└── sso76-image-stream.json

5 directories, 9 files
```

```
$ for resource in sso76-image-stream.json \
         passthrough/sso76-https.json \
         passthrough/sso76-postgresql.json \
         passthrough/sso76-postgresql-persistent.json \
         reencrypt/ocp-3.x/sso76-ocp3-x509-https.json \
         reencrypt/ocp-3.x/sso76-ocp3-x509-postgresql-persistent.json
       do
         oc replace -n openshift --force -f \
https://raw.githubusercontent.com/iankko/redhat-sso-7-openshift-image/RHSSO-2205/templates/${resource}
       done
imagestream.image.openshift.io "postgresql13-for-sso76-openshift-rhel8" deleted
imagestream.image.openshift.io "sso76-openshift-rhel8" deleted
imagestream.image.openshift.io/postgresql13-for-sso76-openshift-rhel8 replaced
imagestream.image.openshift.io/sso76-openshift-rhel8 replaced
template.template.openshift.io/sso76-https replaced
template.template.openshift.io/sso76-postgresql replaced
template.template.openshift.io/sso76-postgresql-persistent replaced
template.template.openshift.io/sso76-ocp3-x509-https replaced
template.template.openshift.io/sso76-ocp3-x509-postgresql-persistent replaced
```

```
$ oc get templates -n openshift | grep sso76
sso76-https                                         An example application based on RH-SSO 7.6 on OpenJDK image. For more informa...   27 (16 blank)     6
sso76-ocp3-x509-https                               An example application based on RH-SSO 7.6 on OpenJDK image. For more informa...   13 (7 blank)      4
sso76-ocp3-x509-postgresql-persistent               An example application based on RH-SSO 7.6 on OpenJDK image. For more informa...   24 (9 blank)      9
sso76-postgresql                                    An example application based on RH-SSO 7.6 on OpenJDK image. For more informa...   34 (18 blank)     8
sso76-postgresql-persistent                         An example application based on RH-SSO 7.6 on OpenJDK image. For more informa...   35 (18 blank)     9
```

```
$ oc describe template sso76-ocp3-x509-https -n openshift | grep -oP 'Message:.*'
Message:	A new RH-SSO service has been created in your project. The admin username/password for accessing the master realm via the RH-SSO console is ${SSO_ADMIN_USERNAME}/${SSO_ADMIN_PASSWORD}. The HTTPS keystore used for serving secure content, the JGroups keystore used for securing JGroups communications, and server truststore used for securing RH-SSO requests were automatically created via OpenShift's service serving x509 certificate secrets using the service-serving CA bundle from '/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt'. Refer to: https://github.com/openshift/openshift-docs/blob/enterprise-4.1/release_notes/ocp-4-1-release-notes.adoc#service-ca-bundle-changes for additional details about this CA bundle.
```

**Review by drichtarik — APPROVED** [review]
LGTM
Thanks for the update. Makes things more clear

**Comment by andymunro** [comment]
Thanks for including me, @iankko.  Looks good.

**Comment by iankko** [comment]
@drichtarik @andymunro Thank you both for prompt review!, merging

**Pull request merged**
