### PR TITLE
KEYCLOAK-12570 redhat-sso-7-openshift-image needs a cct modules update

### PR DESCRIPTION
**Pull request by drichtarik**
@iankko

### CODE REVIEW

**Review by iankko — CHANGES_REQUESTED** [review]
@drichtarik _os-eap7-openshift_ module is listed twice in the [final form of the _image.yaml_ file](https://github.com/jboss-container-images/redhat-sso-7-openshift-image/blob/798ef722ae410925de834722696d49e265137717/image.yaml) Please drop the 2nd occurrence of it.

Though I don't think this change was introduced by your changes, it's better to keep the list of modules sane.

Otherwise LGTM.

**Comment by drichtarik** [comment]
Edited.

**Comment by drichtarik** [comment]
Edited. Missclicked the close button previously..

**Review by iankko — APPROVED** [review]
LGTM

@drichtarik Thanks!

**Pull request merged**
