### PR TITLE
 CIAM-2174 Merge container builds to one multiarch build and use OpenJDK for all architectures

### PR DESCRIPTION
**Pull request by drichtarik**
@iankko @pskopek

### CODE REVIEW

**Comment by iankko** [comment]
@drichtarik The image / modules changes LGTM. But how about the templates / other (case insensitive) mentions of `OpenJ9`. Are we going to remove them too? (see below):

```
$ git clone -b CIAM-2174 git@github.com:drichtarik/redhat-sso-7-openshift-image.git
$ cd redhat-sso-7-openshift-image/
$ grep -irHn 'openj9' * | wc -l
89
```

IOW there are still 89 mentions of OpenJ9. Are we going to remove those too? (like said, the rest of the changes LGTM)

**Comment by drichtarik** [comment]
I don't know. We can, then even the overrides file can go too. I figured, since they are not used, i just ignored them. It's probably better to clean up to code and delete all of them. But then, overrides are useless too and without overrides, more changes to the keycloak-pipeline have to be made.

**Comment by drichtarik** [comment]
Maybe we can do a Jira ticket for later to stop using overrides (which requires more work) and remove all openj9 templates now with this PR

**Comment by iankko** [comment]
> I don't know. We can, then even the overrides file can go too. I figured, since they are not used, i just ignored them. It's probably better to clean up to code and delete all of them. But then, overrides are useless too and without overrides, more changes to the keycloak-pipeline have to be made.

I would say the `openj9` overrides file can be kept as `an example how to do the overrides`. Leave it there. And remove the rest (not really needed).

Sounds OK?

**Comment by drichtarik** [comment]
@iankko check again please

**Comment by iankko** [comment]
> @iankko check again please

@drichtarik The latest version LGTM. Same case-insensitive grep on `openj9` returns only couple of entries:
```
[iankko@localhost redhat-sso-7-openshift-image]$ git config --get remote.origin.url
git@github.com:drichtarik/redhat-sso-7-openshift-image.git
```

```
[iankko@localhost redhat-sso-7-openshift-image]$ grep -irHn 'openj9' *
cekit-build.sh:8:#JDK=openj9
modules/eap/setup/eap/modules/configure.sh:106:# an OpenJDK-specific path. This causes problems for OpenJ9 containers
overrides/openj9.yaml:3:name: "rh-sso-7/sso75-openj9-openshift-rhel8"
overrides/openj9.yaml:4:description: "Red Hat Single Sign-On 7.5 on OpenJ9 OpenShift container image, based on the Red Hat Universal Base Image 8 Minimal container image"
overrides/openj9.yaml:8:      value: "redhat-sso-7-sso75-openj9-openshift-rhel8-container"
overrides/openj9.yaml:26:            branch: rh-sso-7.5-openj9-rhel-8
overrides/openj9.yaml:27:      koji_target: rh-sso-7.5-openj9-rhel-8-containers-candidate
```
But all of those are OK AFAICT. ACK

**Review by iankko — APPROVED** [review]
LGTM (see previous comment)

**Pull request merged**
