### PR TITLE
[KEYCLOAK-15633] Add support for "${prefix}_CONNECTION_PROPERTY_*" for non-XA datasources too

### PR DESCRIPTION
**Pull request by iankko**
<hr/>

<b>Note (for myself):</b> Once the change is accepted / merged, the value of `POSTGRESQL_SOURCE_REPOSITORY_URL` variable from `sso75-x509-postgresql-persistent.json` template needs to be updated to point to the main jboss-container-images RH-SSO images repository (rather than my fork of it).

<hr/>

<u>TL;DR: The short summary of the (intentionally kept separate) commits is as follows:</u>

1. Add `s2i` build definition to enable SSL/TLS support for RHSCL RHEL-7 PostgreSQL server container image,
2. Start PostgreSQL server with SSL/TLS by default when launched from `"sso75-x509-postgresql-persistent.json"` template
3. Add support for injection of connection properties specified via `${prefix}_CONNECTION_PROPERTY_*` environment variables passed to RH-SSO container image. These connection properties would be added to the definition of each non-XA datasource, that would be configured for the image

<hr/>

To test:

1. `oc new-project postgresql-ssl-demo`
2. `oc import-image <image_location>:<image_tag> --insecure=true --confirm`
3. `oc get is` and save the image stream name & image stream tag from it
4. Modify `from:` element / field of the RH-SSO DeploymentConfig of the `"sso75-x509-postgresql-persistent.json"` from this PR to contain the image stream name & image stream tag obtained in previous step. Example:
```
$ diff /tmp/sso75-x509-postgresql-persistent.json.orig /tmp/sso75-x509-postgresql-persistent.json
395,396c395
<                                 "namespace": "${IMAGE_STREAM_NAMESPACE}",
<                                 "name": "sso75-openshift-rhel8:7.5"
---
>                                 "name": "rh-sso-7-sso75-openshift-rhel8:rh-sso-7.5-rhel-8-containers-candidate-50841-20211026141326"

```
IOW the `"namespace"` field was removed, the image to be searched in the current namespace (instead of the default `openshift` one). And image stream name & image stream tag were updated to match the actual values.
5. Create instance of the modified template
    ``` oc create -f /tmp/sso75-x509-postgresql-persistent.json```
6. (Optional) Verify it got created correctly:
  ```
  $ oc get templates
NAME                               DESCRIPTION                                                                        PARAMETERS     OBJECTS
sso75-x509-postgresql-persistent   An example application based on RH-SSO 7.5 on OpenJDK image. For more informa...   24 (9 blank)   9
  ```
7.  Deploy the RH-SSO pod using the modified template
  ```
  $ oc new-app --template=sso75-x509-postgresql-persistent
  ```
8.  Modify the `sso` deployment to contain various `DB_CONNECTION_PROPERTY_*` (& possibly also combined with `DB_XA_CONNECTION_PROPERTY_*` env vars) and confirm they were properly set on the underlying `<datasource ` definition (and / or `<xa-datasource` definition) respectively.

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
@vmuzikar @jonathanvila PTAL (once got a chance)

For now the changes are intentionally left as `Draft PR` instead of a real one. Need to test the changes more thoroughly (especialli the `cli` configuration mode part). Once done, will switch it to a real one.

See the dedicated comment on the KEYCLOAK-15633 JIRA for information about available testing image.

Thanks, Jan

**Comment by iankko** [comment]
Updated testing container image (containing also fix for CIAM-1394 issue not to clash for special characters, possibly present e.g. in password) is available via the pipeline run:
* https://keycloak.jenkins.server.com/view/RH-SSO/job/rh-sso-pipeline-continuous_container/329/

See the corresponding JIRA comment for detailed scenario, how it was (manually) tested.

**Comment by iankko** [comment]
@jonathanvila @ASzc @drichtarik @pskopek PTAL (once got a chance)

Thanks,
Jan

**Comment by iankko** [comment]
@jonathanvila @vmuzikar jFYI, I am going to remove the CIAM-1495 commit from this PR. It isn't working properly anyway / need more time looking at it.

**Comment by iankko** [comment]
JFTR dropped the WIP fix for CIAM-1495 from this one (it's not ready yet -- will be done later in a separate PR) & rebased this one to current upstream `sso75-dev` branch

Should be ready for review once operator testing of RH-SSO images finished. @vmuzikar @jonathanvila Could you kindly report those results here, once you got them?

Thx!
Jan

**Comment by ASzc** [comment]
I don't see any errors in the script changes, although I can't comment on if the whole thing works or not

**Pull request merged**
