### PR TITLE
[CIAM-718] Rebase maven-repo.zip to JBEAP-7.4.2.GA-CR1 version

### PR DESCRIPTION
**Pull request by iankko**
[CIAM-718] Rebase maven-repo.zip to JBEAP-7.4.2.GA-CR1 version
    (MD5 115acd5c7fbcaea84f843c593e850515)
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

Corresponding container pipeline run:
* https://keycloak.jenkins.com/view/RH-SSO/job/rh-sso-pipeline-continuous_container/315/

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
@ASzc Just wanted to be sure RH-SSO 7.5.X will build properly on top of image builder maven repo zip archive from JBEAP-7.4.2.GA-CR1 version (MD5 _115acd5c7fbcaea84f843c593e850515_) thus created a testing build & this PR ahead of CIAM-1169

As for the RH-SSO 7.5.1.GA-CR1 / JBEAP-7.4.2.GA-CR1 rebase -- CIAM-1169 PR:

1. Feel free to close this one & rebase both of RH-SSO & EAP within CIAM-1169 as usual,
2. Or keep this one, and prepare / perform just rebase to RH-SSO 7.5.1.CR / GA

as you wish / based on which option your prefer. Either way WFM

@pskopek @drichtarik PTAL once got a chance

Thx
Jan

**Comment by drichtarik** [comment]
The file has been moved to the released server.

**Comment by ASzc** [comment]
LGTM

**Comment by drichtarik** [comment]
It could have been changed to the released path because this is going to get deleted soon

**Pull request merged**
