### PR TITLE
[KEYCLOAK-10923] Update to RH-SSO 7.3.3

### PR DESCRIPTION
**Pull request by pskopek**

### CODE REVIEW

**Review by martin-kanis — APPROVED** [review]

**Comment by iankko** [comment]
@pskopek I think we also need to update `cct_module` sprint version from [`sprint-35`](https://github.com/jboss-container-images/redhat-sso-7-openshift-image/blob/d1d80e4e812c9ad83911f59ee662f539742d8257/image.yaml#L58) to `0.35.1` tag, IOW perform change like this:

```
diff --git a/image.yaml b/image.yaml
index fcaddd4..4881120 100644
--- a/image.yaml
+++ b/image.yaml
@@ -55,11 +55,11 @@ modules:
           - name: cct_module
             git:
                   url: https://github.com/jboss-openshift/cct_module.git
-                  ref: sprint-35
+                  ref: 0.35.1
           - name: jboss-eap-modules
             git:
                   url: https://github.com/jboss-container-images/jboss-eap-modules.git
-                  ref: EAP_722_CR1
+                  ref: EAP_723_CR2
           - name: sso73_modules
             path: modules
       install:
```

Here's why -- [comparing `sprint-35` to `0.35.1` changes](https://github.com/jboss-openshift/cct_module/compare/sprint-35...0.35.1) returns the version of Jolokia was updated (from `1.5.0-redhat-1` to `1.6.2-redhat-00002` one). And looking into EAP OpenShift image returns:

```
[iankko@unknown tmp]$ docker run -it 2bac94b46ee1 /bin/bash
[jboss@6a452449fada ~]$ find / 2>/dev/null -name jolokia*
/opt/jboss/container/jolokia
/opt/jboss/container/jolokia/jolokia-jvm-1.6.2.redhat-00002-agent.jar
/opt/jboss/container/jolokia/jolokia-opts
/opt/jboss/container/jolokia/jolokia.jar
/opt/eap/bin/probes/probe/eap/jolokia.py
/opt/eap/bin/probes/probe/jolokia.py
/opt/eap/jolokia.jar
/opt/jolokia
[jboss@6a452449fada ~]$ 
```
IOW the EAP OpenShift image uses `jolokia-jvm-1.6.2.redhat-00002-agent.jar` already. So we should mirror the EAP approach (not to create new product with different Jolokia version, not to need to maintain by ourselves it if an future issue occurs).

@luck3y @rgdoliveira PTAL -^. Can you confirm the expected EAP 7.2.3 Jolokia version is `1.6.2-redhat-00002` one? Thanks!, Jan

**Comment by iankko** [comment]
@pskopek The rest of the change LGTM (once the cct_module sprint value is updated).

**Review by iankko — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by rgdoliveira** [comment]
@iankko yes, EAP 7.2.3 OS image contains jolokia version 1.6.2-redhat-00002.

**Comment by pskopek** [comment]
Thanks @rgdoliveira !

**Review by iankko — APPROVED** [review]

**Comment by iankko** [comment]
The latest version LGTM. @rgdoliveira Thanks for confirmation!, @pskopek Thanks for fixing!

**Pull request merged**
