### PR TITLE
KEYCLOAK-12699 Do not generate Keystore on empty /etc/x509/https dir

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.redhat.com/browse/KEYCLOAK-12699

### CODE REVIEW

**Comment by hmlnarik** [comment]
@mhajas Could you please review this PR?

**Review by iankko — APPROVED** [review]
LGTM

**Comment by mhajas** [comment]
@pskopek please do not merge this PR yet. It is not critical for this release. We can revisit this for next release after a further discussion.

**Comment by iankko** [comment]
@mhajas @pskopek Can we go ahead and merge this one? Or would you like to perform further review yet?

**Comment by mhajas** [comment]
@iankko I would say it is ok.

**Comment by iankko** [comment]
> @iankko I would say it is ok.

@mhajas great, thank you Michal!

**Pull request merged**
