### PR TITLE
[KEYCLOAK-8165] Update RH-SSO TP CD image stream to start

### PR DESCRIPTION
**Pull request by iankko**
using registry.redhat.io TBR and local image reference policy

Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
@rcernich @Crumby PTAL (once got a chance)

Thank you, Jan

**Comment by iankko** [comment]
JFTR, to test this you will need to create secret containing the user credentials to pull the images from the registry and link it to the `default` service account. See [relevant section of OCP v3.10 docs](https://docs.openshift.com/container-platform/3.10/dev_guide/managing_images.html#allowing-pods-to-reference-images-from-other-secured-registries) for further details.

Tested the change locally, and seems to be working fine for me.

**Review by rcernich — APPROVED** [review]
LGTM

I believe the idea is that there would be a global config for the pull secret, which would be setup by the cluster-admin.

**Review by rcernich — APPROVED** [review]
lgtm

**Comment by rcernich** [comment]
@iankko, could you push this, if it's ready to go?  The other pr's associated with CLOUD-2752 have been pushed.  If you need to hold off on this, let's clone the issue and move this pr to the new issue.

**Comment by iankko** [comment]
@rcernich Done

**Pull request merged**
