### PR TITLE
KEYCLOAK-17245 Make number of owners configurable

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.redhat.com/browse/KEYCLOAK-17245

The approach has been synchronized with the upstream: https://github.com/keycloak/keycloak-containers/blob/master/server/tools/cli/infinispan/cache-owners.cli

@pskopek @mposolda

### CODE REVIEW

**Review by iankko — APPROVED** [review]
/lgtm Thanks, @slaskawi 

P.S.: Did I get it correctly, the cache owners count is intended to be adjusted / customized
via the ```CACHE_OWNERS_COUNT``` / ```CACHE_OWNERS_AUTH_SESSIONS_COUNT``` being passed to the image (JVM CLI) e.g. the ```JAVA_OPTS_APPEND``` variable?

One note yet (though can be done in a follow-up JIRA if necessary): Could the added variable be described in the docs too? Yet, should it be added as a new templates paramater, where appropriate, so it's customizable more easily? (right after image provisioning from the template)

**Comment by iankko** [comment]
@pskopek @sguilhen LGTM, but leaving for you to merge this one within the upcoming RH-SSO image release, when it's appropriate (the time for it comes).

@Pepo48 @ivioi2e2 PTAL once got a chance (if it's OK from your PoV too)

Thanks!
Jan

**Comment by Aboullos** [comment]
LGTM

**Comment by slaskawi** [comment]
> P.S.: Did I get it correctly, the cache owners count is intended to be adjusted / customized
via the CACHE_OWNERS_COUNT / CACHE_OWNERS_AUTH_SESSIONS_COUNT being passed to the image (JVM CLI) e.g. the JAVA_OPTS_APPEND variable?

@iankko It's simpler than that - you just need to put those environment variables on the image. Wildfly will pick them up automagically.

> One note yet (though can be done in a follow-up JIRA if necessary): Could the added variable be described in the docs too? Yet, should it be added as a new templates paramater, where appropriate, so it's customizable more easily? (right after image provisioning from the template)

@iankko Ok, good idea.

**Comment by slaskawi** [comment]
@iankko Documentation updated.

**Comment by iankko** [comment]
> @iankko Documentation updated.

@slaskawi Great, thank you!

**Pull request merged**
