### PR TITLE
[CLOUD-4044] Enableing IBM Semeru java for openj9 images sso74 cpaas

### PR DESCRIPTION
**Pull request by levivic**
https://issues.redhat.com/browse/CLOUD-4044
Signed-off-by: Lei Zhang <lzhan@redhat.com>

- [x] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted
- [x] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
Jenkins testing build against RH-SSO 7.4.9.CR1 / GA:
* https://keycloak.jenkins.server.com//view/RH-SSO/job/rh-sso-pipeline-continuous_container/218/console

**Review by iankko — COMMENTED** [review]
@levivic Thank you for the change!

LGTM AFAICT (but will postpone the approval bit till the testing build [*] finished & we can see the result)

Thanks,
Jan

[*] Added (obfuscated) link to it as comment. Check with me for a real one if / once needed

**Comment by drichtarik** [comment]
Approved if the test build runs ok. I'll update here when the test run is finished

**Comment by drichtarik** [comment]
Test run done

**Review by iankko — APPROVED** [review]
LGTM AFAICT -- the image was built properly & seems to be running OK with custom options. 

See quick test on ppc64le machine below for details:

```
# docker run -it -e SSO_ADMIN_USERNAME=admin -e SSO_ADMIN_PASSWORD=admin -e SSO_REALM=demorealm 3b914da4e81e
WARN No password defined for JGroups cluster. AUTH protocol will be disabled. Please define JGROUPS_CLUSTER_PASSWORD.
...
14:12:53,346 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
14:12:53,350 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Red Hat Single Sign-On 7.4.9.GA (WildFly Core 10.1.23.Final-redhat-00001) started in 27718ms - Started 670 of 970 services (687 services are lazy, passive or on-demand)
14:12:53,353 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
14:12:53,353 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
```

**Comment by iankko** [comment]
@sguilhen jFYI, merging this one, so @drichtarik can rebuild the OpenJ9 image (see the review above).

**Pull request merged**
