### PR TITLE
[CLOUD-3662] Adding ppc64le to builds

### PR DESCRIPTION
**Pull request by lysannef**
Signed-off-by: lyfernan <lyfernan@redhat.com>

Pull request with additions to support ppc64le builds alongside s390x.
https://issues.redhat.com/browse/CLOUD-3662

### CODE REVIEW

**Comment by lysannef** [comment]
@hmlnarik  Can these changes please be reviewed , in order to be able to trigger ppc64le builds alongside s390x

**Review by hmlnarik — APPROVED** [review]
Thanks @lysannef. The changes look good, but I defer to @pskopek and @pdrozd to merge this PR to consider the sync the changes with the forthcoming release. Note also that this PR only updates product image but there are other images related to the operator.
cc: @slaskawi @ASzc

**Comment by lysannef** [comment]
@hmlnarik  @pskopek @pdrozd 
As per my understanding the changes for the operator build are added to the dist-git repository . Kindly let me know if any additional changes needed to this Pull request.

**Comment by lysannef** [comment]
@hmlnarik @pskopek @pdrozd
Any changes needed ?

**Review by pskopek — APPROVED** [review]
It looks fine!

**Pull request merged**
